spring.application.name=scalecrm
# PostgreSQL Configuration (pgAdmin 4)
spring.datasource.url=jdbc:postgresql://localhost:5432/crmdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console (Disabled since we use PostgreSQL/pgAdmin now)
spring.h2.console.enabled=false

# Security
jwt.secret=94a08da1fecbb6e8b46990538c7b50b25e2439366d21f8a8462002364e1c5dbb
jwt.expiration=86400000

# Error Handling (Custom mapping for frontend routes)
spring.web.resources.add-mappings=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
